databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: './build.sh'  # Ensure this script is executable
    startCommand: 'gunicorn dynamic_mail_services.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  
  - type: backgroundWorker  # ADD THIS
    name: mysite-celery
    runtime: python
    plan: free
    buildCommand: './build.sh'  # Or simplified: 'pip install -r requirements.txt'
    startCommand: 'celery -A dynamic_mail_services worker --loglevel=info'
    envVars:
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: your-redis  # Reference your existing Redis Key Value
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: dynamic_mail_services.settings